'use strict';
const stage=document.querySelector('#stage'),scenarioSelect=document.querySelector('#scenario'),storeKey='game1006-design-a-v2';
const wrap=body=>`<svg viewBox="0 0 64 64" aria-hidden="true" fill="none" stroke="#55705a" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round">${body}</svg>`;
const icons={house:wrap('<path fill="#f5e4be" d="M10 28 32 10l22 18v27H10z"/><path fill="#c48466" d="m6 29 26-23 26 23-5 4-21-18-21 18z"/><path fill="#aec1a3" d="M25 55V35h14v20"/><circle cx="34" cy="45" r="1"/>'),chair:wrap('<path fill="#c99a6a" d="M17 9h28v23H17zM14 34h36v10H14z"/><path d="M18 44v13m28-13v13M18 32V15m28 17V15"/>'),flowers:wrap('<path d="M32 42V19m-2 20L19 30m15 7 10-9"/><path fill="#dc9f91" d="M23 16q-8-10 2-11 7-3 8 5 8-7 12 1 3 8-6 10 5 10-5 11-9 0-10-8-10 0-8-7z"/><circle cx="31" cy="19" r="5" fill="#edcf81"/><path fill="#c68e6c" d="m17 42 5 17h20l5-17z"/>'),tree:wrap('<path d="M29 37h7v23h-7z" fill="#b58a62"/><path fill="#a9c08c" d="M14 38Q3 25 16 18 14 5 29 8 44-2 48 15q17 7 8 21-6 13-20 7-13 9-22-5Z"/>'),path:wrap('<path fill="#e8d6b2" d="m5 17 17-6 7 13-9 10-16-4zm29-7 23 3 3 17-17 6-15-10zM10 40l15-8 14 13-10 15-21-4zm32 0 16-2 3 19-22 4-5-11z"/>'),pond:wrap('<path fill="#a2c9bd" d="M4 33C4 9 29 8 41 15S65 36 53 47 4 59 4 33Z"/><path d="M12 32q8 5 14 0m5 8q11 5 20-2"/><ellipse cx="41" cy="25" rx="8" ry="4" fill="#aec591"/>'),swing:wrap('<path d="m5 57 9-48h36l9 48M18 11v30m28-30v30"/><path fill="#c99a6a" d="M15 41h34v7H15z"/>'),table:wrap('<ellipse cx="32" cy="25" rx="27" ry="14" fill="#d2aa7c"/><path d="M15 35v23m34-23v23M30 38v14"/>'),bed:wrap('<path fill="#d4bd98" d="M8 16h48v40H8z"/><path fill="#aec1a3" d="M11 28h42v22H11z"/><rect x="15" y="18" width="34" height="12" rx="5" fill="#fffdf6"/><path d="M8 56v5m48-5v5"/>'),rug:wrap('<path d="m4 34 28-19 28 19-28 19z" fill="#dfb8a0"/><path d="m15 34 17-10 17 10-17 10z"/>')};
const propSlots={tree:0,chair:1,table:2,bed:3,flowers:4,house:5,path:6,pond:7,swing:8,rug:9};
const propSizes={tree:28,chair:13,table:19,bed:24,flowers:9,house:35,path:14,pond:28,swing:25,rug:24};
function propWidth(o){const indoor=o.room!=='outside';const base=propSizes[o.kind]*(indoor?1:(['chair','table','bed','flowers','rug'].includes(o.kind)?.7:1));return base*(.8+(o.y-40)*.006);}
function propArt(o){const n=propSlots[o.kind];return `<span class="prop" style="background-position:${n%5*25}% ${n>=5?100:0}%;transform:scaleX(${o.angle%360>=180?-1:1});${o.kind==='house'&&o.color?'filter:hue-rotate('+([0,25,-15][o.color]||0)+'deg)':''}"></span>`;}
function inPolygon(x,y,points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const [xi,yi]=points[i],[xj,yj]=points[j];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))inside=!inside;}return inside;}
function placementError(o){
 if(!o)return '';
 if(o.room!=='outside'){
  if(!inPolygon(o.x,o.y,[[12,59],[54,42],[87,60],[68,86],[28,85]]))return 'Place it on the wooden floor, away from walls and doors.';
 }else{
  if(o.x<8||o.x>91||o.y<49||o.y>87)return 'Place it on the lower lawn or beside the path.';
  if(inPolygon(o.x,o.y,[[66,46],[99,46],[99,66],[72,65]]))return 'This is the pond. Try the lawn.';
  if(o.x<37&&o.y<55)return 'This is the house. Try the lawn.';
 }
 const w=propWidth(o);
 if(o.x-w*.42<0||o.x+w*.42>100)return 'Too close to the edge. Move it inward.';
 const blocked=world.some(other=>{if(other.room!==o.room||other.id===o.id||other.kind==='rug'||o.kind==='rug'||other.kind==='path'||o.kind==='path')return false;const rx=(w+propWidth(other))*.27,ry=(w+propWidth(other))*.1;return ((other.x-o.x)/rx)**2+((other.y-o.y)/ry)**2<1;});
 return blocked?'Too close to another item. Leave a little space.':'';
}
function findOpenSpot(o){const candidates=o.room==='outside'?[[24,77],[43,80],[68,79],[23,64],[48,66]]:[[38,63],[65,65],[51,78],[29,75],[66,80]];for(let y=54;y<=85;y+=5)for(let x=15;x<=85;x+=5)candidates.push([x,y]);for(const [x,y]of candidates){const test={...o,x,y};if(!placementError(test))return test;}return {...o,x:48,y:70};}
const houseColors=['#f5e4be','#b8c8a3','#e0b0a0'];
const names={house:'Cabin',chair:'Chair',flowers:'Flower pot',tree:'Tree',path:'Path',pond:'Pond',swing:'Swing',table:'Round table',bed:'Bed',rug:'Rug'};
const roles=[{name:'Sunny',color:'#edcf81',hair:'#514037'},{name:'Sky',color:'#a8c3cf',hair:'#79563c'},{name:'Peach',color:'#dfa79b',hair:'#4f3830'},{name:'Leaf',color:'#a9bc91',hair:'#6b4e36'}];
function avatar(i){const r=roles[i];return `<svg viewBox="0 0 80 100" aria-hidden="true"><path d="M14 54Q6 6 39 5q36 0 28 51" fill="${r.hair}"/><path d="M16 100V83q0-22 24-22t24 22v17" fill="${r.color}"/><ellipse cx="40" cy="38" rx="25" ry="27" fill="#f1c9a8"/><path d="M15 34Q13 9 39 9q27 0 26 24L46 19 30 31Z" fill="${r.hair}"/><circle cx="30" cy="40" r="3" fill="#493d35"/><circle cx="50" cy="40" r="3" fill="#493d35"/><path d="M34 53q6 6 12 0" stroke="#a36c58" stroke-width="2" fill="none"/></svg>`;}
let catalogExpanded=true;
let world=[],undoStack=[],role=0,view='roles',room='outside',draft=null,selected=null,modal=null,condition='normal',sitting=false,emptyPreview=false,notice='',saveFailed=false;
try{const data=JSON.parse(localStorage.getItem(storeKey)||'[]');if(Array.isArray(data))world=data.filter(x=>x&&names[x.kind]&&['outside','inside','empty'].includes(x.room)&&typeof x.id==='string'&&Number.isFinite(x.x)&&Number.isFinite(x.y)&&Number.isFinite(x.angle)).map(x=>({...x,x:Math.max(8,Math.min(92,x.x)),y:Math.max(30,Math.min(87,x.y)),angle:x.angle%360}));}catch{notice='Could not read the preview save. You can decorate again.';}
function save(){if(condition==='savefail'){saveFailed=true;return;}try{localStorage.setItem(storeKey,JSON.stringify(world));saveFailed=false;document.querySelector('#local-state').textContent='Preview saved on this device';}catch{saveFailed=true;document.querySelector('#local-state').textContent='Could not save this preview';}}
function checkpoint(){undoStack.push(JSON.stringify(world));}
function currentRoom(){return emptyPreview&&room==='inside'?'empty':room;}
function draftValid(){return !!draft&&!placementError(draft);}
function objectHTML(o,ghost=false){const w=propWidth(o),z=(o.kind==='rug'||o.kind==='path')?1:Math.floor(o.y*10);return `<button class="object ${ghost?'ghost':''} ${o.id===selected?'selected':''} ${ghost&&!draftValid()?'invalid':''}" style="left:${o.x}%;top:${o.y}%;width:${w}%;z-index:${z}" ${ghost?'tabindex="-1"':`data-object="${o.id}"`} aria-label="${names[o.kind]}, Select to edit">${propArt(o)}<span class="footprint"></span>${ghost||o.id===selected?`<small>${names[o.kind]}</small>`:''}</button>`;}
function itemsHTML(){const kinds=room==='outside'?['house','chair','flowers','tree','path','pond','swing']:['chair','table','bed','flowers','rug'];return kinds.map(k=>`<button class="item" data-item="${k}"><span class="thumb">${propArt({kind:k,angle:0,y:65})}</span>${names[k]}</button>`).join('');}
function buttonsHTML(){if(draft)return `<div class="bottom-row"><strong>${names[draft.kind]}</strong><button data-action="rotate">↔ Turn</button>${draft.kind==='house'?'<button data-action="color">Change color</button>':''}<button data-action="cancel-draft">Cancel</button><button class="primary right" data-action="place" ${draftValid()?'':'disabled'}>Place here</button></div>`;if(selected)return `<div class="bottom-row"><strong>${names[world.find(o=>o.id===selected)?.kind]||'Item'}</strong>${world.find(o=>o.id===selected)?.kind==='house'?'<button data-action="color">Change color</button>':''}<button data-action="move">Move</button><button data-action="rotate-existing">↔ Turn</button><button class="danger" data-action="remove">Put away</button><button class="right" data-action="deselect">Done</button></div>`;if((view==='build'||view==='inside')&&!catalogExpanded)return `<div class="bottom-row"><strong>${room==='inside'?'Decorate the cabin':'Decorate the garden'}</strong><button data-action="undo" ${undoStack.length?'':'disabled'}>Undo</button><button data-action="walk">Explore</button><button class="primary right" data-action="more">＋ Add more</button></div>`;if(view==='build'||view==='inside')return `<div class="catalog-title"><strong>${room==='inside'?'Make the cabin your own':'What would you like to place?'}</strong><small>All items free · Place duplicates</small><button data-action="undo" ${undoStack.length?'':'disabled'}>Undo</button><button data-action="walk">Explore</button></div><div class="items">${itemsHTML()}</div>`;return `<div class="bottom-row"><strong>${room==='inside'?'Inside the cabin':'In the town'}</strong><button data-action="undo" ${undoStack.length?'':'disabled'}>Undo</button><button class="primary right" data-action="build">Decorate</button></div>`;}
function dialogHTML(){if(modal==='remove')return `<h2>Put this away?</h2><p>You can get another from the catalog, or undo this action.</p><div class="bottom-row"><button data-action="close">Keep it</button><button class="primary" data-action="confirm-remove">Put it away</button></div>`;if(modal==='reset')return `<h2>Restart this preview?</h2><p>This only clears the preview layout in this browser.</p><div class="bottom-row"><button data-action="close">Keep</button><button class="primary" data-action="confirm-reset">Restart</button></div>`;if(modal==='offline')return `<h2>Disconnected from the town</h2><p>Decorating is paused until we reconnect.</p><div class="bottom-row"><button class="primary" data-action="retry">Reconnect</button></div>`;if(modal==='full')return `<h2>The town is full right now</h2><p>Four friends are playing. Wait for a free spot.</p><div class="bottom-row"><button data-action="roles">Back to characters</button><button class="primary" data-action="retry">Try again</button></div>`;if(modal==='occupied')return `<h2>Sky is moving it</h2><p>Wait until they finish, or decorate something else.</p><div class="bottom-row"><button class="primary" data-action="close">Got it</button></div>`;if(modal==='swing'){return `<h2>${sitting?'Gently swaying':'Time for a swing'}</h2><svg class="swingart" viewBox="0 0 200 190" aria-hidden="true"><path d="M15 175 40 25h120l25 150" fill="none" stroke="#aa835b" stroke-width="10" stroke-linecap="round"/><g class="${sitting?'swing-motion':''}"><path d="M67 25v112m66-112v112" stroke="#b69770" stroke-width="4"/>${sitting?`<circle cx="100" cy="79" r="22" fill="#f1c9a8"/><path d="M78 74q0-33 23-27 23 0 23 27l-28-12z" fill="${roles[role].hair}"/><path d="M84 133V104h32v29" fill="${roles[role].color}"/><path d="M92 138v22m16-22v22" stroke="#e4bb97" stroke-width="9" stroke-linecap="round"/>`:''}<rect x="58" y="133" width="84" height="10" rx="5" fill="#b78a61"/></g></svg><p>${sitting?'Stay a while. Tap Get off when you are ready.':'Tap to sit down. No tricky controls.'}</p><div class="bottom-row"><button data-action="close">${sitting?'Get off and return':'Not now'}</button>${sitting?'':'<button class="primary" data-action="sit">Sit down</button>'}</div>`;}return '';}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));stage.className='stage'+(view==='roles'?' choosing':'')+(draft?' placing':'');let html=`<img class="backdrop" src="${room==='inside'?'interior.png':'scene-a.png'}" alt="${room==='inside'?'An empty cabin to decorate':'Town concept A'}">`;
if(view==='roles'){html+=`<div class="welcome"><span class="eyebrow">Welcome to the town</span><h2>Who will you be today?</h2><p>Choose a friend to join the town.</p><div class="roles">${roles.map((r,i)=>`<button class="role" data-role="${i}" aria-pressed="${i===role}">${avatar(i)}${r.name}</button>`).join('')}</div><button class="primary" data-action="join">Let&#39;s go to town</button><p>Character names and looks are draft ideas.</p></div>`;}else{html+=`<div class="hud"><div class="pill">${roles[role].name} · ${room==='inside'?'Cabin':'Shared home'}<small>● ● ● ○　3 / 4 friends · Example</small></div><div class="pill">${saveFailed?'Not saved yet':'✓ Home saved'}<small>${saveFailed?'Please retry before leaving':'Local preview state'}</small></div></div><div class="hint" aria-live="polite">${notice||(draft?(draftValid()?'A free spot! Drag elsewhere or tap Place here.':placementError(draft)):selected?'Move, turn or put away':room==='inside'?'Choose some furniture to make the cabin cozy.':'Tap the door to enter, or try the swing.')}</div>`;
if(!draft&&!selected)html+=room==='inside'?'<button class="hotspot exit" data-action="outside">Go outside</button>':'<button class="hotspot door" data-action="inside">Enter cabin</button><button class="hotspot swing" data-action="swing">Play on swing</button>';
html+=world.filter(o=>o.room===currentRoom()&&o.id!==draft?.id).sort((a,b)=>a.y-b.y).map(o=>objectHTML(o)).join('');if(draft)html+=objectHTML(draft,true);html+=`<div class="bottom">${buttonsHTML()}${saveFailed?'<div class="bottom-row"><span>Changes have not been saved</span><button data-action="retry-save">Retry save</button></div>':''}</div>`;}
if(modal)html+=`<div class="overlay"><div class="dialog" role="dialog" aria-modal="true" tabindex="-1">${dialogHTML()}</div></div>`;stage.innerHTML=html;localize();if(modal)stage.querySelector('.dialog').focus({preventScroll:true});}
function navigate(next){catalogExpanded=true;view=next;draft=null;selected=null;modal=null;sitting=false;notice='';if(next==='roles'||next==='outside'||next==='build'||next==='swing')room='outside';if(next==='inside')room='inside';if(next==='swing'){view='outside';modal='swing';}render();}
function act(action){notice='';switch(action){case'more':catalogExpanded=true;break;case'join':if(condition==='full'){modal='full';break;}navigate('outside');return;case'roles':navigate('roles');return;case'build':catalogExpanded=true;view=room==='inside'?'inside':'build';break;case'walk':view='outside';draft=null;selected=null;break;case'inside':navigate('inside');return;case'outside':emptyPreview=false;navigate('outside');return;case'swing':modal='swing';break;case'sit':sitting=true;break;case'close':modal=null;sitting=false;break;case'color':if(draft){draft.color=((draft.color||0)+1)%3;}else{checkpoint();world=world.map(o=>o.id===selected?{...o,color:((o.color||0)+1)%3}:o);save();}break;case'rotate':draft.angle=(draft.angle+180)%360;break;case'cancel-draft':draft=null;selected=null;break;case'place':if(!draftValid())return;checkpoint();world=world.filter(o=>o.id!==draft.id);world.push({...draft});catalogExpanded=false;draft=null;selected=null;save();notice='Placed! You can add another one.';break;case'deselect':selected=null;break;case'move':draft={...world.find(o=>o.id===selected)};break;case'rotate-existing':checkpoint();world=world.map(o=>o.id===selected?{...o,angle:(o.angle+180)%360}:o);save();break;case'remove':modal='remove';break;case'confirm-remove':checkpoint();world=world.filter(o=>o.id!==selected);selected=null;modal=null;save();notice='Put away. Tap Undo to restore it.';break;case'undo':if(undoStack.length){world=JSON.parse(undoStack.pop());selected=null;draft=null;save();notice='Last action undone.';}break;case'retry':condition='normal';scenarioSelect.value='normal';modal=null;if(view==='roles')view='outside';notice='Connected to town · Simulation';break;case'retry-save':condition='normal';scenarioSelect.value='normal';save();notice=saveFailed?'Still not saved. Please keep this page open.':'Saved again · Local preview';break;case'confirm-reset':world=[];undoStack=[];condition='normal';scenarioSelect.value='normal';emptyPreview=false;save();navigate('roles');return;}render();}
let dragging=false;
function pointDraft(event){const r=stage.getBoundingClientRect();draft.x=Math.round((event.clientX-r.left)/r.width*100);draft.y=Math.round((event.clientY-r.top)/r.height*100);notice='';render();}
stage.addEventListener('pointerdown',event=>{if(!draft||event.target.closest('.bottom,.hud,.overlay,button:not(.object)'))return;dragging=true;stage.setPointerCapture(event.pointerId);pointDraft(event);});
stage.addEventListener('pointermove',event=>{if(dragging&&draft)pointDraft(event);});
stage.addEventListener('pointerup',()=>{dragging=false;});
stage.addEventListener('pointercancel',()=>{dragging=false;});
stage.addEventListener('click',event=>{const button=event.target.closest('button');if(button){if(button.dataset.role!==undefined){role=Number(button.dataset.role);render();return;}if(button.dataset.item){draft=findOpenSpot({id:crypto.randomUUID(),kind:button.dataset.item,room:currentRoom(),angle:0});selected=null;notice='';render();return;}if(button.dataset.object){if(draft)return;if(condition==='occupied'){modal='occupied';}else{selected=button.dataset.object;draft=null;notice='';}render();return;}if(button.dataset.action)act(button.dataset.action);return;}if(draft&&!event.target.closest('.bottom,.hud,.overlay')){const rect=stage.getBoundingClientRect();draft.x=Math.round((event.clientX-rect.left)/rect.width*100);draft.y=Math.round((event.clientY-rect.top)/rect.height*100);notice='';render();}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(condition==='offline')return;navigate(b.dataset.view);});
scenarioSelect.onchange=()=>{condition=scenarioSelect.value;notice='';modal=null;draft=null;selected=null;emptyPreview=condition==='empty';saveFailed=condition==='savefail';if(condition==='offline')modal='offline';if(condition==='full'){view='roles';room='outside';modal='full';}if(condition==='savefail'){view='build';room='outside';}if(condition==='empty'){view='inside';room='inside';}if(condition==='occupied'){view='build';room='outside';modal='occupied';}render();};
document.querySelector('#reset').onclick=()=>{modal='reset';render();};
stage.addEventListener('keydown',e=>{if(e.key==='Tab'&&modal){const controls=[...stage.querySelectorAll('.dialog button:not(:disabled)')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
render();

document.addEventListener('localechange', render);
