## Every placeable object. All entries are free and unlimited; nothing is unlocked.
##
## Fields:
##   name      English source string (translated through the locale catalogs)
##   category  catalog tab
##   space     "town", "home" (inside a house) or "both"
##   radius    footprint circle in meters used for overlap and walking collision
##   layer     "solid" blocks walking and other solids; "flat" lies on the ground
##             and only collides with other flat items
##   color     default paint index (see palette.gd); -1 means not paintable
##   seats     how many children can sit/ride at once (0 = not interactive)
##   action    context action label key for seated items
##   model     optional GLB scene (modeled assets); otherwise built in props.gd
##   size_class, anchor, bounds, tabletop_eligible, support_surface:
##             the object scale and surface contract, see
##             design/object-scale-and-surfaces.md (1 unit = 1 m, H = 1.30)
##
## To add an object designed by the creator: add an entry here, a builder in
## scripts/art/props.gd and its English name to every file in game/locale/.
extends RefCounted

const ITEMS := {
	"cottage": {"name": "Cottage", "category": "Homes", "space": "town", "radius": 2.3, "layer": "solid", "color": 2, "seats": 0, "size_class": "landmark", "anchor": "ground", "bounds": Vector3(3.8, 7.51, 3.6), "tabletop_eligible": false},
	"tree": {"name": "Round tree", "category": "Nature", "space": "town", "radius": 0.55, "layer": "solid", "color": 5, "seats": 0, "size_class": "tree", "anchor": "ground", "bounds": Vector3(1.85, 2.42, 1.85), "tabletop_eligible": false},
	"pine": {"name": "Pine tree", "category": "Nature", "space": "town", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "tree", "anchor": "ground", "bounds": Vector3(1.5, 2.18, 1.5), "tabletop_eligible": false},
	"bush": {"name": "Berry bush", "category": "Nature", "space": "town", "radius": 0.6, "layer": "solid", "color": 3, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(1.31, 0.96, 0.99), "tabletop_eligible": false},
	"flowers": {"name": "Flower patch", "category": "Nature", "space": "town", "radius": 0.45, "layer": "solid", "color": 3, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.83, 0.51, 0.83), "tabletop_eligible": false},
	"path_stone": {"name": "Stepping stone", "category": "Paths & water", "space": "town", "radius": 0.45, "layer": "flat", "color": -1, "seats": 0, "size_class": "flat", "anchor": "ground", "bounds": Vector3(1.04, 0.1, 0.97), "tabletop_eligible": false},
	"pond": {"name": "Pond", "category": "Paths & water", "space": "town", "radius": 2.0, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(4.19, 1.06, 3.61), "tabletop_eligible": false},
	"lamp_post": {"name": "Lamp post", "category": "Paths & water", "space": "town", "radius": 0.3, "layer": "solid", "color": 1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(0.56, 3.03, 0.56), "tabletop_eligible": false},
	"fence": {"name": "Fence", "category": "Paths & water", "space": "town", "radius": 0.6, "layer": "solid", "color": 0, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(1.3, 0.85, 0.16), "tabletop_eligible": false},
	"swing": {"name": "Swing", "category": "Play", "space": "town", "radius": 1.3, "layer": "solid", "color": 4, "seats": 1, "action": "Swing", "size_class": "large", "anchor": "ground", "bounds": Vector3(2.4, 2.35, 1.52), "tabletop_eligible": false},
	"seesaw": {"name": "Seesaw", "category": "Play", "space": "town", "radius": 1.5, "layer": "solid", "color": 1, "seats": 2, "action": "Ride", "size_class": "large", "anchor": "ground", "bounds": Vector3(0.5, 0.98, 3.0), "tabletop_eligible": false},
	"bench": {"name": "Bench", "category": "Play", "space": "town", "radius": 0.85, "layer": "solid", "color": 5, "seats": 2, "action": "Sit", "size_class": "large", "anchor": "ground", "bounds": Vector3(1.6, 0.94, 0.54), "tabletop_eligible": false},
	"blanket": {"name": "Picnic blanket", "category": "Play", "space": "town", "radius": 1.0, "layer": "flat", "color": 3, "seats": 0, "size_class": "flat", "anchor": "ground", "bounds": Vector3(1.8, 0.47, 1.4), "tabletop_eligible": false},
	"bed": {"name": "Bed", "category": "Furniture", "space": "home", "radius": 0.95, "layer": "solid", "color": 5, "seats": 1, "action": "Rest", "size_class": "large", "anchor": "ground", "bounds": Vector3(1.28, 0.96, 1.98), "tabletop_eligible": false},
	"chair": {"name": "Chair", "category": "Furniture", "space": "both", "radius": 0.4, "layer": "solid", "color": 0, "seats": 1, "action": "Sit", "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.52, 1.0, 0.52), "tabletop_eligible": false},
	"table": {"name": "Round table", "category": "Furniture", "space": "both", "radius": 0.65, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.2, 0.7, 1.2), "tabletop_eligible": false,
		"support_surface": {"local_position": Vector3(0, 0.70, 0), "usable_size_xz": Vector2(0.84, 0.84), "max_items": 1}},
	"sofa": {"name": "Sofa", "category": "Furniture", "space": "home", "radius": 0.9, "layer": "solid", "color": 4, "seats": 2, "action": "Sit", "size_class": "large", "anchor": "ground", "bounds": Vector3(1.8, 0.86, 0.82), "tabletop_eligible": false},
	"bookshelf": {"name": "Bookshelf", "category": "Furniture", "space": "home", "radius": 0.6, "layer": "solid", "color": 6, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.1, 1.6, 0.44), "tabletop_eligible": false},
	"rug": {"name": "Rug", "category": "Cozy things", "space": "home", "radius": 1.15, "layer": "flat", "color": 2, "seats": 0, "size_class": "flat", "anchor": "ground", "bounds": Vector3(2.2, 0.04, 1.58), "tabletop_eligible": false},
	"plant": {"name": "Flower pot", "category": "Cozy things", "space": "both", "radius": 0.25, "layer": "solid", "color": 0, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.38, 0.52, 0.36), "tabletop_eligible": true},
	"floor_lamp": {"name": "Floor lamp", "category": "Cozy things", "space": "home", "radius": 0.3, "layer": "solid", "color": 1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.6, 1.62, 0.6), "tabletop_eligible": false},
	"teddy": {"name": "Teddy bear", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": 7, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.35, 0.45, 0.27), "tabletop_eligible": true},
	# Modeled furniture from the reviewed pilot-10 handoff (art/pilot-10-v1). Scale is
	# baked into the GLB; bounds and footprints come from its manifests.
	"scallop_chair": {"name": "Scallop chair", "category": "Furniture", "space": "both", "radius": 0.38, "layer": "solid", "color": -1, "seats": 1, "action": "Sit", "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.533, 1.068, 0.501), "tabletop_eligible": false, "model": "res://assets/models/scallop_chair.glb"},
	"cozy_round_table": {"name": "Cozy round table", "category": "Furniture", "space": "both", "radius": 0.52, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 0.66, 1.0), "tabletop_eligible": false, "model": "res://assets/models/cozy_round_table.glb",
		"support_surface": {"local_position": Vector3(0, 0.66, 0), "usable_size_xz": Vector2(0.56, 0.56), "max_items": 1}},
	"scallop_bed": {"name": "Scallop bed", "category": "Furniture", "space": "home", "radius": 0.85, "layer": "solid", "color": -1, "seats": 1, "action": "Rest", "size_class": "large", "anchor": "ground", "bounds": Vector3(1.072, 1.018, 1.792), "tabletop_eligible": false, "model": "res://assets/models/scallop_bed.glb"},
	"writing_bureau": {"name": "Writing desk", "category": "Furniture", "space": "home", "radius": 0.38, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(0.78, 0.95, 0.516), "tabletop_eligible": false, "model": "res://assets/models/writing_bureau.glb"},
	"open_shelf": {"name": "Open shelf", "category": "Furniture", "space": "home", "radius": 0.45, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.001, 1.362, 0.401), "tabletop_eligible": false, "model": "res://assets/models/open_shelf.glb"},
	"curved_counter": {"name": "Curved counter", "category": "Furniture", "space": "home", "radius": 0.62, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.51, 0.8, 0.578), "tabletop_eligible": false, "model": "res://assets/models/curved_counter.glb"},
	"desk_lamp": {"name": "Desk lamp", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.317, 0.538, 0.482), "tabletop_eligible": true, "model": "res://assets/models/desk_lamp.glb"},
	"flower_pot_bloom": {"name": "Blooming flower pot", "category": "Cozy things", "space": "both", "radius": 0.18, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.351, 0.573, 0.351), "tabletop_eligible": true, "model": "res://assets/models/flower_pot_bloom.glb"},
	# Wall and ceiling items (rooms only). They hang instead of standing: see
	# design/object-scale-and-surfaces.md. Origins: clock center on the wall plane,
	# mobile at its ceiling hook.
	"wall_clock": {"name": "Wall clock", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "mount_height": 1.5, "bounds": Vector3(0.44, 0.44, 0.141), "tabletop_eligible": false, "model": "res://assets/models/wall_clock.glb"},
	"bird_mobile": {"name": "Bird mobile", "category": "Cozy things", "space": "home", "radius": 0.41, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ceiling", "bounds": Vector3(0.817, 0.78, 0.78), "tabletop_eligible": false, "model": "res://assets/models/bird_mobile.glb"},
	# BEGIN production models r1 (generated by tools/nookipedia-model-production/tools/integrate_release.py;
	# frozen, validated batches b001-b008; original geometry, references used for function and size only)
	"acoustic_guitar_stand": {"name": "Guitar on a stand", "category": "Furniture", "space": "home", "radius": 0.25, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.327, 0.932, 0.365), "tabletop_eligible": false, "model": "res://assets/models/acoustic_guitar_stand.glb"},
	"antique_console_table": {"name": "Console table", "category": "Furniture", "space": "home", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 0.73, 0.428), "tabletop_eligible": false, "model": "res://assets/models/antique_console_table.glb", "support_surface": {"local_position": Vector3(0, 0.73, 0), "usable_size_xz": Vector2(0.84, 0.36), "max_items": 1}},
	"antique_vanity": {"name": "Vanity with mirror", "category": "Furniture", "space": "home", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 1.27, 0.467), "tabletop_eligible": false, "model": "res://assets/models/antique_vanity.glb"},
	"antique_wardrobe": {"name": "Old wardrobe", "category": "Furniture", "space": "home", "radius": 0.55, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.08, 1.575, 0.638), "tabletop_eligible": false, "model": "res://assets/models/antique_wardrobe.glb"},
	"apple_chair": {"name": "Apple chair", "category": "Furniture", "space": "home", "radius": 0.38, "layer": "solid", "color": -1, "seats": 1, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.57, 1.001, 0.553), "tabletop_eligible": false, "model": "res://assets/models/apple_chair.glb", "action": "Sit"},
	"arcade_cabinet_blue": {"name": "Blue arcade game", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.632, 1.46, 0.75), "tabletop_eligible": false, "model": "res://assets/models/arcade_cabinet_blue.glb"},
	"arcade_cabinet_keys": {"name": "Tile arcade game", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.632, 1.46, 0.75), "tabletop_eligible": false, "model": "res://assets/models/arcade_cabinet_keys.glb"},
	"arcade_cabinet_red": {"name": "Red arcade game", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.632, 1.46, 0.75), "tabletop_eligible": false, "model": "res://assets/models/arcade_cabinet_red.glb"},
	"cash_machine": {"name": "Cash machine", "category": "Furniture", "space": "home", "radius": 0.38, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.64, 1.2, 0.62), "tabletop_eligible": false, "model": "res://assets/models/cash_machine.glb"},
	"celebratory_arch_gold": {"name": "Golden party arch", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.94, 1.746, 0.356), "tabletop_eligible": false, "model": "res://assets/models/celebratory_arch_gold.glb"},
	"celebratory_arch_teal": {"name": "Teal party arch", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.94, 1.746, 0.356), "tabletop_eligible": false, "model": "res://assets/models/celebratory_arch_teal.glb"},
	"handled_urn": {"name": "Handled urn", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.482, 0.515, 0.335), "tabletop_eligible": true, "model": "res://assets/models/handled_urn.glb"},
	"pedestal_side_table": {"name": "Pedestal side table", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.75, 0.801, 0.75), "tabletop_eligible": false, "model": "res://assets/models/pedestal_side_table.glb", "support_surface": {"local_position": Vector3(0, 0.8, 0), "usable_size_xz": Vector2(0.49, 0.49), "max_items": 1}},
	"practice_amp": {"name": "Practice amp", "category": "Cozy things", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.52, 0.52, 0.327), "tabletop_eligible": false, "model": "res://assets/models/practice_amp.glb"},
	"tall_case_clock": {"name": "Grandfather clock", "category": "Furniture", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.48, 1.47, 0.341), "tabletop_eligible": false, "model": "res://assets/models/tall_case_clock.glb"},
	"anatomy_model": {"name": "Anatomy model", "category": "Furniture", "space": "home", "radius": 0.25, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.445, 1.11, 0.4), "tabletop_eligible": false, "model": "res://assets/models/anatomy_model.glb"},
	"anchor_statue": {"name": "Anchor statue", "category": "Furniture", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.552, 0.936, 0.54), "tabletop_eligible": false, "model": "res://assets/models/anchor_statue.glb"},
	"cushion_stool": {"name": "Cushion stool", "category": "Cozy things", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 1, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.468, 0.546, 0.468), "tabletop_eligible": false, "model": "res://assets/models/cushion_stool.glb", "action": "Sit"},
	"egg_lounge_chair": {"name": "Egg lounge chair", "category": "Furniture", "space": "home", "radius": 0.38, "layer": "solid", "color": -1, "seats": 1, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.62, 1.05, 0.691), "tabletop_eligible": false, "model": "res://assets/models/egg_lounge_chair.glb", "action": "Sit"},
	"folding_screen": {"name": "Folding screen", "category": "Furniture", "space": "home", "radius": 0.55, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.123, 1.2, 0.21), "tabletop_eligible": false, "model": "res://assets/models/folding_screen.glb"},
	"insect_house": {"name": "Bug house", "category": "Furniture", "space": "home", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 0.79, 0.56), "tabletop_eligible": false, "model": "res://assets/models/insect_house.glb"},
	"lab_machine": {"name": "Lab machine", "category": "Furniture", "space": "home", "radius": 0.6, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.1, 1.165, 0.536), "tabletop_eligible": false, "model": "res://assets/models/lab_machine.glb"},
	"lattice_cabinet": {"name": "Lattice cabinet", "category": "Furniture", "space": "home", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 0.86, 0.448), "tabletop_eligible": false, "model": "res://assets/models/lattice_cabinet.glb"},
	"low_platform_bed": {"name": "Low platform bed", "category": "Furniture", "space": "home", "radius": 0.85, "layer": "solid", "color": -1, "seats": 1, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.08, 0.94, 1.86), "tabletop_eligible": false, "model": "res://assets/models/low_platform_bed.glb", "action": "Rest"},
	"oval_arch_table": {"name": "Oval table", "category": "Furniture", "space": "home", "radius": 0.55, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.12, 0.66, 0.58), "tabletop_eligible": false, "model": "res://assets/models/oval_arch_table.glb", "support_surface": {"local_position": Vector3(0, 0.66, 0), "usable_size_xz": Vector2(0.74, 0.36), "max_items": 1}},
	"paper_floor_lamp": {"name": "Paper floor lamp", "category": "Furniture", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.3, 1.36, 0.297), "tabletop_eligible": false, "model": "res://assets/models/paper_floor_lamp.glb"},
	"ram_rocker": {"name": "Ram rocker", "category": "Furniture", "space": "home", "radius": 0.4, "layer": "solid", "color": -1, "seats": 1, "size_class": "large", "anchor": "ground", "bounds": Vector3(0.476, 0.759, 1.069), "tabletop_eligible": false, "model": "res://assets/models/ram_rocker.glb", "action": "Sit"},
	"saxophone_stand": {"name": "Saxophone on a stand", "category": "Furniture", "space": "home", "radius": 0.25, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.438, 0.868, 0.338), "tabletop_eligible": false, "model": "res://assets/models/saxophone_stand.glb"},
	"slat_armchair": {"name": "Slatted armchair", "category": "Furniture", "space": "home", "radius": 0.38, "layer": "solid", "color": -1, "seats": 1, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.58, 0.923, 0.582), "tabletop_eligible": false, "model": "res://assets/models/slat_armchair.glb", "action": "Sit"},
	"wooden_signpost": {"name": "Signpost", "category": "Furniture", "space": "home", "radius": 0.25, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.507, 1.2, 0.309), "tabletop_eligible": false, "model": "res://assets/models/wooden_signpost.glb"},
	"baby_crib": {"name": "Baby crib", "category": "Furniture", "space": "home", "radius": 0.45, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.688, 0.895, 0.968), "tabletop_eligible": false, "model": "res://assets/models/baby_crib.glb"},
	"ball_cart": {"name": "Ball cart", "category": "Furniture", "space": "home", "radius": 0.5, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 0.74, 0.637), "tabletop_eligible": false, "model": "res://assets/models/ball_cart.glb"},
	"bamboo_basket": {"name": "Bamboo basket", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.338, 0.409, 0.338), "tabletop_eligible": true, "model": "res://assets/models/bamboo_basket.glb"},
	"bamboo_bench": {"name": "Bamboo bench", "category": "Furniture", "space": "home", "radius": 0.55, "layer": "solid", "color": -1, "seats": 1, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.2, 0.465, 0.426), "tabletop_eligible": false, "model": "res://assets/models/bamboo_bench.glb", "action": "Sit"},
	"bamboo_floor_lantern": {"name": "Bamboo floor lantern", "category": "Furniture", "space": "home", "radius": 0.26, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.44, 1.03, 0.44), "tabletop_eligible": false, "model": "res://assets/models/bamboo_floor_lantern.glb"},
	"bamboo_noodle_slide": {"name": "Bamboo noodle slide", "category": "Furniture", "space": "home", "radius": 0.9, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(2.219, 0.866, 0.4), "tabletop_eligible": false, "model": "res://assets/models/bamboo_noodle_slide.glb"},
	"bamboo_partition": {"name": "Bamboo partition", "category": "Furniture", "space": "home", "radius": 0.55, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.0, 1.35, 0.24), "tabletop_eligible": false, "model": "res://assets/models/bamboo_partition.glb"},
	"bamboo_ring_shelf": {"name": "Bamboo ring shelf", "category": "Furniture", "space": "home", "radius": 0.6, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(1.176, 1.229, 0.42), "tabletop_eligible": false, "model": "res://assets/models/bamboo_ring_shelf.glb"},
	"child_tube_chair": {"name": "Little tube chair", "category": "Cozy things", "space": "home", "radius": 0.26, "layer": "solid", "color": -1, "seats": 1, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.384, 0.555, 0.391), "tabletop_eligible": false, "model": "res://assets/models/child_tube_chair.glb", "action": "Sit"},
	"garden_pavilion": {"name": "Garden pavilion", "category": "Furniture", "space": "home", "radius": 1.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(2.8, 2.81, 2.8), "tabletop_eligible": false, "model": "res://assets/models/garden_pavilion.glb"},
	"glowing_bamboo": {"name": "Glowing bamboo", "category": "Furniture", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.491, 0.8, 0.435), "tabletop_eligible": false, "model": "res://assets/models/glowing_bamboo.glb"},
	"space_rock": {"name": "Space rock", "category": "Furniture", "space": "home", "radius": 0.42, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(0.918, 0.728, 0.837), "tabletop_eligible": false, "model": "res://assets/models/space_rock.glb"},
	"space_suit_display": {"name": "Space suit display", "category": "Furniture", "space": "home", "radius": 0.28, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.608, 1.27, 0.52), "tabletop_eligible": false, "model": "res://assets/models/space_suit_display.glb"},
	"top_load_washer": {"name": "Washing machine", "category": "Furniture", "space": "home", "radius": 0.36, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.6, 1.005, 0.61), "tabletop_eligible": false, "model": "res://assets/models/top_load_washer.glb"},
	"wish_bamboo": {"name": "Wishing bamboo", "category": "Furniture", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.757, 1.439, 0.798), "tabletop_eligible": false, "model": "res://assets/models/wish_bamboo.glb"},
	"accessory_rack": {"name": "Accessory rack", "category": "Furniture", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "medium", "anchor": "ground", "bounds": Vector3(0.58, 0.842, 0.332), "tabletop_eligible": false, "model": "res://assets/models/accessory_rack.glb"},
	"aluminum_briefcase": {"name": "Metal briefcase", "category": "Cozy things", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.5, 0.419, 0.154), "tabletop_eligible": true, "model": "res://assets/models/aluminum_briefcase.glb"},
	"anchovy_model": {"name": "Little fish model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.4, 0.341, 0.22), "tabletop_eligible": true, "model": "res://assets/models/anchovy_model.glb"},
	"angelfish_model": {"name": "Angelfish model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.389, 0.486, 0.22), "tabletop_eligible": true, "model": "res://assets/models/angelfish_model.glb"},
	"ant_farm": {"name": "Ant farm", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.37, 0.5, 0.14), "tabletop_eligible": true, "model": "res://assets/models/ant_farm.glb"},
	"ant_model": {"name": "Ant model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.335, 0.319), "tabletop_eligible": true, "model": "res://assets/models/ant_model.glb"},
	"butterfly_model": {"name": "Butterfly model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.332, 0.244), "tabletop_eligible": true, "model": "res://assets/models/butterfly_model.glb"},
	"circulator_fan": {"name": "Little fan", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.375, 0.46, 0.22), "tabletop_eligible": true, "model": "res://assets/models/circulator_fan.glb"},
	"clay_figurine": {"name": "Clay figure", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.445, 0.558, 0.241), "tabletop_eligible": true, "model": "res://assets/models/clay_figurine.glb"},
	"fried_fish_plate": {"name": "Fried fish plate", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.267, 0.36), "tabletop_eligible": true, "model": "res://assets/models/fried_fish_plate.glb"},
	"garlic_fish_skillet": {"name": "Fish skillet", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.422, 0.27, 0.36), "tabletop_eligible": true, "model": "res://assets/models/garlic_fish_skillet.glb"},
	"kitchen_scale": {"name": "Kitchen scale", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.33, 0.302, 0.33), "tabletop_eligible": true, "model": "res://assets/models/kitchen_scale.glb"},
	"tiered_tea_stand": {"name": "Tea stand", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.32, 0.572, 0.32), "tabletop_eligible": true, "model": "res://assets/models/tiered_tea_stand.glb"},
	"apple_jam_jars": {"name": "Apple jam jars", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.29, 0.286, 0.18), "tabletop_eligible": true, "model": "res://assets/models/apple_jam_jars.glb"},
	"apple_jelly_plate": {"name": "Apple jelly", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.324, 0.36), "tabletop_eligible": true, "model": "res://assets/models/apple_jelly_plate.glb"},
	"apple_pie_plate": {"name": "Apple pie", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.288, 0.36), "tabletop_eligible": true, "model": "res://assets/models/apple_pie_plate.glb"},
	"apple_smoothie": {"name": "Apple smoothie", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.251, 0.331, 0.18), "tabletop_eligible": true, "model": "res://assets/models/apple_smoothie.glb"},
	"apple_tart_slice": {"name": "Apple tart slice", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.275, 0.36), "tabletop_eligible": true, "model": "res://assets/models/apple_tart_slice.glb"},
	"arapaima_model": {"name": "Big fish model", "category": "Furniture", "space": "home", "radius": 0.45, "layer": "solid", "color": -1, "seats": 0, "size_class": "large", "anchor": "ground", "bounds": Vector3(0.921, 0.379, 0.24), "tabletop_eligible": false, "model": "res://assets/models/arapaima_model.glb"},
	"arched_table_radio": {"name": "Table radio", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.419, 0.226), "tabletop_eligible": true, "model": "res://assets/models/arched_table_radio.glb"},
	"aroma_burner": {"name": "Aroma burner", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.28, 0.278, 0.28), "tabletop_eligible": true, "model": "res://assets/models/aroma_burner.glb"},
	"arowana_model": {"name": "Silver fish model", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.409, 0.363, 0.22), "tabletop_eligible": true, "model": "res://assets/models/arowana_model.glb"},
	"backlit_box_sign": {"name": "Lit sign", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.42, 0.3, 0.167), "tabletop_eligible": true, "model": "res://assets/models/backlit_box_sign.glb"},
	"brass_cash_register": {"name": "Cash register", "category": "Cozy things", "space": "home", "radius": 0.26, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.481, 0.36, 0.338), "tabletop_eligible": true, "model": "res://assets/models/brass_cash_register.glb"},
	"map_on_easel": {"name": "Map on an easel", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.372, 0.343, 0.197), "tabletop_eligible": true, "model": "res://assets/models/map_on_easel.glb"},
	"plush_bear": {"name": "Plush bear", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.361, 0.44, 0.242), "tabletop_eligible": true, "model": "res://assets/models/plush_bear.glb"},
	"plush_panda": {"name": "Plush panda", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.361, 0.44, 0.242), "tabletop_eligible": true, "model": "res://assets/models/plush_panda.glb"},
	"bagworm_model": {"name": "Bagworm model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.41, 0.22), "tabletop_eligible": true, "model": "res://assets/models/bagworm_model.glb"},
	"baked_potatoes_plate": {"name": "Baked potatoes", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.31, 0.36), "tabletop_eligible": true, "model": "res://assets/models/baked_potatoes_plate.glb"},
	"bamboo_candle_cup": {"name": "Bamboo candle", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.278, 0.388, 0.246), "tabletop_eligible": true, "model": "res://assets/models/bamboo_candle_cup.glb"},
	"bamboo_lunch_basket": {"name": "Bamboo lunch box", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.47, 0.29, 0.252), "tabletop_eligible": true, "model": "res://assets/models/bamboo_lunch_basket.glb"},
	"bamboo_shoot_lamp": {"name": "Bamboo shoot lamp", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.26, 0.48, 0.264), "tabletop_eligible": true, "model": "res://assets/models/bamboo_shoot_lamp.glb"},
	"bamboo_shoot_soup": {"name": "Bamboo shoot soup", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.283, 0.36), "tabletop_eligible": true, "model": "res://assets/models/bamboo_shoot_soup.glb"},
	"bamboo_slit_drum": {"name": "Bamboo drum", "category": "Cozy things", "space": "home", "radius": 0.3, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.46, 0.295, 0.36), "tabletop_eligible": true, "model": "res://assets/models/bamboo_slit_drum.glb"},
	"baseball_set": {"name": "Baseball set", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.554, 0.349, 0.281), "tabletop_eligible": false, "model": "res://assets/models/baseball_set.glb"},
	"basketball": {"name": "Basketball", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.35, 0.352, 0.352), "tabletop_eligible": true, "model": "res://assets/models/basketball.glb"},
	"bath_bucket": {"name": "Bath bucket", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.413, 0.298, 0.38), "tabletop_eligible": false, "model": "res://assets/models/bath_bucket.glb"},
	"beach_ball": {"name": "Beach ball", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.345, 0.34), "tabletop_eligible": true, "model": "res://assets/models/beach_ball.glb"},
	"berliner_plate": {"name": "Jam doughnut", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.305, 0.36), "tabletop_eligible": true, "model": "res://assets/models/berliner_plate.glb"},
	"cricket_model": {"name": "Cricket model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.34, 0.344, 0.372), "tabletop_eligible": true, "model": "res://assets/models/cricket_model.glb"},
	"deep_sea_fish_model": {"name": "Deep-sea fish model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.383, 0.374, 0.22), "tabletop_eligible": true, "model": "res://assets/models/deep_sea_fish_model.glb"},
	"fish_carpaccio_plate": {"name": "Fish carpaccio", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.36, 0.265, 0.36), "tabletop_eligible": true, "model": "res://assets/models/fish_carpaccio_plate.glb"},
	"striped_fish_model": {"name": "Striped fish model", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.411, 0.419, 0.22), "tabletop_eligible": true, "model": "res://assets/models/striped_fish_model.glb"},
	"woven_bamboo_sphere": {"name": "Woven bamboo ball", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "solid", "color": -1, "seats": 0, "size_class": "small", "anchor": "ground", "bounds": Vector3(0.338, 0.369, 0.338), "tabletop_eligible": true, "model": "res://assets/models/woven_bamboo_sphere.glb"},
	"bamboo_wall_spray": {"name": "Bamboo wall spray", "category": "Cozy things", "space": "home", "radius": 0.1, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.209, 0.33, 0.12), "tabletop_eligible": false, "model": "res://assets/models/bamboo_wall_spray.glb", "mount_height": 1.5},
	"blue_rose_wreath": {"name": "Blue rose wreath", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.452, 0.481, 0.083), "tabletop_eligible": false, "model": "res://assets/models/blue_rose_wreath.glb", "mount_height": 1.5},
	"broom_and_dustpan": {"name": "Broom and dustpan", "category": "Cozy things", "space": "home", "radius": 0.17, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.346, 0.699, 0.092), "tabletop_eligible": false, "model": "res://assets/models/broom_and_dustpan.glb", "mount_height": 1.5},
	"bust_relief_plaque": {"name": "Portrait plaque", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.36, 0.435, 0.148), "tabletop_eligible": false, "model": "res://assets/models/bust_relief_plaque.glb", "mount_height": 1.5},
	"butterfly_plaque": {"name": "Butterfly plaque", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.36, 0.435, 0.078), "tabletop_eligible": false, "model": "res://assets/models/butterfly_plaque.glb", "mount_height": 1.5},
	"egg_bow_wreath": {"name": "Egg wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.486, 0.537, 0.097), "tabletop_eligible": false, "model": "res://assets/models/egg_bow_wreath.glb", "mount_height": 1.5},
	"egg_light_garland": {"name": "Egg light garland", "category": "Cozy things", "space": "home", "radius": 0.47, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.93, 0.22, 0.069), "tabletop_eligible": false, "model": "res://assets/models/egg_light_garland.glb", "mount_height": 1.5},
	"egg_wall_clock": {"name": "Egg wall clock", "category": "Cozy things", "space": "home", "radius": 0.19, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.382, 0.5, 0.095), "tabletop_eligible": false, "model": "res://assets/models/egg_wall_clock.glb", "mount_height": 1.5},
	"fish_trophy_wall": {"name": "Fish trophy", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.462, 0.33, 0.065), "tabletop_eligible": false, "model": "res://assets/models/fish_trophy_wall.glb", "mount_height": 1.5},
	"framed_painting_night": {"name": "Night painting", "category": "Cozy things", "space": "home", "radius": 0.5, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(1.0, 0.8, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_night.glb", "mount_height": 1.5},
	"framed_painting_portrait": {"name": "Portrait painting", "category": "Cozy things", "space": "home", "radius": 0.25, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.5, 0.85, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_portrait.glb", "mount_height": 1.5},
	"framed_painting_ring": {"name": "Ring painting", "category": "Cozy things", "space": "home", "radius": 0.25, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.5, 0.62, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_ring.glb", "mount_height": 1.5},
	"green_bulletin_board": {"name": "Bulletin board", "category": "Cozy things", "space": "home", "radius": 0.4, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.8, 0.5, 0.066), "tabletop_eligible": false, "model": "res://assets/models/green_bulletin_board.glb", "mount_height": 1.5},
	"round_award_plaque": {"name": "Award plaque", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.4, 0.4, 0.062), "tabletop_eligible": false, "model": "res://assets/models/round_award_plaque.glb", "mount_height": 1.5},
	"signed_card_frames": {"name": "Card frames", "category": "Cozy things", "space": "home", "radius": 0.34, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.68, 0.46, 0.038), "tabletop_eligible": false, "model": "res://assets/models/signed_card_frames.glb", "mount_height": 1.5},
	"towel_rack": {"name": "Towel rack", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.48, 0.35, 0.175), "tabletop_eligible": false, "model": "res://assets/models/towel_rack.glb", "mount_height": 1.5},
	"wall_air_conditioner": {"name": "Air conditioner", "category": "Cozy things", "space": "home", "radius": 0.45, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.9, 0.28, 0.21), "tabletop_eligible": false, "model": "res://assets/models/wall_air_conditioner.glb", "mount_height": 1.5},
	"wall_boomerang": {"name": "Boomerang", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.395, 0.395, 0.06), "tabletop_eligible": false, "model": "res://assets/models/wall_boomerang.glb", "mount_height": 1.5},
	"wall_crank_phone": {"name": "Crank phone", "category": "Cozy things", "space": "home", "radius": 0.18, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.354, 0.34, 0.18), "tabletop_eligible": false, "model": "res://assets/models/wall_crank_phone.glb", "mount_height": 1.5},
	"blossom_wall_clock": {"name": "Blossom clock", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.456, 0.468, 0.093), "tabletop_eligible": false, "model": "res://assets/models/blossom_wall_clock.glb", "mount_height": 1.5},
	"cherry_wall_lamp": {"name": "Cherry wall lamp", "category": "Cozy things", "space": "home", "radius": 0.19, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.377, 0.456, 0.2), "tabletop_eligible": false, "model": "res://assets/models/cherry_wall_lamp.glb", "mount_height": 1.5},
	"chic_cosmos_wreath": {"name": "Chic cosmos wreath", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.453, 0.462, 0.081), "tabletop_eligible": false, "model": "res://assets/models/chic_cosmos_wreath.glb", "mount_height": 1.5},
	"chic_windflower_wreath": {"name": "Chic anemone wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.476, 0.453, 0.083), "tabletop_eligible": false, "model": "res://assets/models/chic_windflower_wreath.glb", "mount_height": 1.5},
	"coconut_wall_planter": {"name": "Coconut planter", "category": "Cozy things", "space": "home", "radius": 0.14, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.252, 0.471, 0.286), "tabletop_eligible": false, "model": "res://assets/models/coconut_wall_planter.glb", "mount_height": 1.5},
	"cool_hyacinth_wreath": {"name": "Cool hyacinth wreath", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.461, 0.46, 0.079), "tabletop_eligible": false, "model": "res://assets/models/cool_hyacinth_wreath.glb", "mount_height": 1.5},
	"cool_pansy_wreath": {"name": "Cool pansy wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.479, 0.47, 0.082), "tabletop_eligible": false, "model": "res://assets/models/cool_pansy_wreath.glb", "mount_height": 1.5},
	"cool_windflower_wreath": {"name": "Cool anemone wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.471, 0.453, 0.083), "tabletop_eligible": false, "model": "res://assets/models/cool_windflower_wreath.glb", "mount_height": 1.5},
	"cork_board": {"name": "Cork board", "category": "Cozy things", "space": "home", "radius": 0.4, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.8, 0.5, 0.066), "tabletop_eligible": false, "model": "res://assets/models/cork_board.glb", "mount_height": 1.5},
	"cosmos_wreath": {"name": "Cosmos wreath", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.47, 0.461, 0.081), "tabletop_eligible": false, "model": "res://assets/models/cosmos_wreath.glb", "mount_height": 1.5},
	"crest_doorplate": {"name": "Crest doorplate", "category": "Cozy things", "space": "home", "radius": 0.21, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.419, 0.397, 0.055), "tabletop_eligible": false, "model": "res://assets/models/crest_doorplate.glb", "mount_height": 1.5},
	"cuckoo_wall_clock": {"name": "Cuckoo clock", "category": "Cozy things", "space": "home", "radius": 0.19, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.371, 0.713, 0.215), "tabletop_eligible": false, "model": "res://assets/models/cuckoo_wall_clock.glb", "mount_height": 1.5},
	"dark_lily_wreath": {"name": "Dark lily wreath", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.452, 0.486, 0.084), "tabletop_eligible": false, "model": "res://assets/models/dark_lily_wreath.glb", "mount_height": 1.5},
	"dark_rose_wreath": {"name": "Dark rose wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.479, 0.47, 0.082), "tabletop_eligible": false, "model": "res://assets/models/dark_rose_wreath.glb", "mount_height": 1.5},
	"dark_tulip_wreath": {"name": "Dark tulip wreath", "category": "Cozy things", "space": "home", "radius": 0.24, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.475, 0.467, 0.082), "tabletop_eligible": false, "model": "res://assets/models/dark_tulip_wreath.glb", "mount_height": 1.5},
	"dried_flower_garland": {"name": "Dried flower garland", "category": "Cozy things", "space": "home", "radius": 0.47, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.93, 0.287, 0.071), "tabletop_eligible": false, "model": "res://assets/models/dried_flower_garland.glb", "mount_height": 1.5},
	"framed_painting_field": {"name": "Field painting", "category": "Cozy things", "space": "home", "radius": 0.31, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.62, 0.5, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_field.glb", "mount_height": 1.5},
	"framed_painting_park": {"name": "Park painting", "category": "Cozy things", "space": "home", "radius": 0.5, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(1.0, 0.72, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_park.glb", "mount_height": 1.5},
	"framed_painting_scroll": {"name": "Scroll painting", "category": "Cozy things", "space": "home", "radius": 0.2, "layer": "mounted", "color": -1, "seats": 0, "size_class": "medium", "anchor": "wall", "bounds": Vector3(0.4, 0.85, 0.067), "tabletop_eligible": false, "model": "res://assets/models/framed_painting_scroll.glb", "mount_height": 1.5},
	"neon_ring_clock": {"name": "Neon clock", "category": "Cozy things", "space": "home", "radius": 0.22, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.44, 0.44, 0.105), "tabletop_eligible": false, "model": "res://assets/models/neon_ring_clock.glb", "mount_height": 1.5},
	"plush_wall_shelf": {"name": "Plush wall shelf", "category": "Cozy things", "space": "home", "radius": 0.25, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.5, 0.408, 0.16), "tabletop_eligible": false, "model": "res://assets/models/plush_wall_shelf.glb", "mount_height": 1.5},
	"station_wall_clock": {"name": "Station clock", "category": "Cozy things", "space": "home", "radius": 0.23, "layer": "mounted", "color": -1, "seats": 0, "size_class": "small", "anchor": "wall", "bounds": Vector3(0.15, 0.338, 0.46), "tabletop_eligible": false, "model": "res://assets/models/station_wall_clock.glb", "mount_height": 1.5},
	# END production models r1
	# A garden bed that grows from seeds to flowers while children play (activity D).
	"garden_bed": {"name": "Garden bed", "category": "Nature", "space": "town", "radius": 0.6, "layer": "solid", "color": 3, "seats": 0, "action": "Water", "size_class": "medium", "anchor": "ground", "bounds": Vector3(1.2, 0.72, 0.9), "tabletop_eligible": false},
}

## Reviewed models that are complete but not placeable yet (none at the moment:
## wall and ceiling anchors now exist and the clock and mobile are integrated).
const PENDING_MODELS := {}

const TOWN_CATEGORIES := ["Nature", "Paths & water", "Play", "Homes", "Furniture"]
const HOME_CATEGORIES := ["Furniture", "Cozy things"]


static func has(kind: String) -> bool:
	return ITEMS.has(kind)


static func get_def(kind: String) -> Dictionary:
	return ITEMS.get(kind, {})


## Visual height of the built model (from the scale contract bounds).
static func height(kind: String) -> float:
	return ITEMS.get(kind, {}).get("bounds", Vector3.ONE).y


## "ground", "wall" or "ceiling".
static func anchor(kind: String) -> String:
	return ITEMS.get(kind, {}).get("anchor", "ground")


static func support_surface(kind: String) -> Dictionary:
	return ITEMS.get(kind, {}).get("support_surface", {})


## True when an item of this kind may sit on a host of that kind, turned by
## rel_steps 45-degree steps relative to the host (eligibility and fit).
static func fits_on(kind: String, host_kind: String, rel_steps := 0) -> bool:
	var surface := support_surface(host_kind)
	var def := get_def(kind)
	if surface.is_empty() or not def.get("tabletop_eligible", false):
		return false
	return fits_surface(def["bounds"], surface, rel_steps)


## The item's footprint box, turned by rel_steps x 45 degrees in the host's frame,
## must lie inside the usable rectangle: no overhang at any rotation.
static func fits_surface(bounds: Vector3, surface: Dictionary, rel_steps := 0) -> bool:
	var a := posmod(rel_steps, 8) * TAU / 8.0
	var w := absf(bounds.x * cos(a)) + absf(bounds.z * sin(a))
	var d := absf(bounds.x * sin(a)) + absf(bounds.z * cos(a))
	var area: Vector2 = surface["usable_size_xz"]
	return w <= area.x + 0.001 and d <= area.y + 0.001


static func allowed_in(kind: String, space: String) -> bool:
	var where: String = ITEMS.get(kind, {}).get("space", "")
	if where == "both":
		return true
	return where == ("town" if space == "town" else "home")


## Kinds shown in one catalog tab for the given space, in a stable order.
static func kinds_for(category: String, space: String) -> Array:
	var out := []
	for kind in ITEMS:
		if ITEMS[kind]["category"] == category and allowed_in(kind, space):
			out.append(kind)
	return out
